# Generated by Django 4.1.3 on 2022-11-29 19:35

import cars.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(default='', max_length=20, validators=[cars.core.validators.validate_name_is_alpha])),
                ('last_name', models.CharField(default='', max_length=20, validators=[cars.core.validators.validate_name_is_alpha])),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(75)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.IntegerField(default=0, unique=True)),
            ],
        ),
    ]
