# Generated by Django 4.1.3 on 2022-11-29 19:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='/profile/default/profile.jpeg', max_length=255, verbose_name='Image'),
        ),
    ]
