# Generated by Django 4.1.3 on 2022-12-03 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : +6591258565', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
    ]
