# Generated by Django 4.1.3 on 2022-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_code',
            field=models.IntegerField(default=0),
        ),
    ]
