# Generated by Django 4.1.3 on 2022-12-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_delete_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteCode',
            fields=[
                ('generated_code', models.IntegerField(blank=True, null=True)),
                ('confirm_delete_code', models.IntegerField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delete_code',
        ),
    ]
