# Generated by Django 4.1.3 on 2022-12-12 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_deletecode_confirm_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=0, max_length=18, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : +3591258565', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
    ]
