#FROM python:3.10
#
## set work directory
#WORKDIR $APP_HOME
#
## set environment variables
#ENV PYTHONDONTWRITEBYTECODE 1
#ENV PYTHONUNBUFFERED 1
#
## install dependencies
#RUN pip install --upgrade pip
#COPY ./requirements.txt /usr/src/app/requirements.txt
#RUN pip install -r requirements.txt
#
## copy entrypoint.sh
##COPY ../entrypoint.sh /usr/src/app/entrypoint.sh
#
## copy project
#COPY . /usr/src/app/

# run entrypoint.sh
#ENTRYPOINT ["/usr/src/app/entrypoint.sh"]