# Generated by Django 4.1.3 on 2022-11-29 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('year_of_manufacture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2022)])),
                ('fuel', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas')], max_length=10)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('touring', 'Touring'), ('coupe', 'Coupe'), ('suv', 'SUV')], max_length=10)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('horse_power', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ad')),
            ],
        ),
    ]
