# Generated by Django 4.1.3 on 2022-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_ad_image1_ad_image2_ad_image3_ad_image_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
