# Generated by Django 4.1.3 on 2022-12-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image1',
            field=models.URLField(default='https://res.cloudinary.com/dltjy2gzz/image/upload/v1669814122/cars/default/no-image-icon-15_p4ng0f.png'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image2',
            field=models.URLField(default='https://res.cloudinary.com/dltjy2gzz/image/upload/v1669814122/cars/default/no-image-icon-15_p4ng0f.png'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image3',
            field=models.URLField(default='https://res.cloudinary.com/dltjy2gzz/image/upload/v1669814122/cars/default/no-image-icon-15_p4ng0f.png'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_main',
            field=models.URLField(default='https://res.cloudinary.com/dltjy2gzz/image/upload/v1669814122/cars/default/no-image-icon-15_p4ng0f.png'),
        ),
    ]
