# Generated by Django 4.1.4 on 2022-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_alter_ad_image1_alter_ad_image2_alter_ad_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='fuel',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('gas', 'Gas')], max_length=15),
        ),
    ]
