# Generated by Django 4.1.4 on 2022-12-21 12:19

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_alter_ad_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dltjy2gzz/image/upload/v1669814122/cars/default/no-image-icon-15_p4ng0f.png', max_length=255, verbose_name='Image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.ad')),
            ],
        ),
    ]
