# Generated by Django 4.1.4 on 2023-05-22 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='year_of_manufacture',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
