# Generated by Django 4.1.4 on 2023-05-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_alter_ad_year_of_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(),
        ),
    ]
